# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  push:
    branches: dev
    
jobs:
  # 각 job별로 환경을 지정 할수 있음
  build:
    # 우분투 최신 버전에서 소스를 빌드하기 위한 설정
    # 깃허브에서 정의한 가상환경 지정
    runs-on: ubuntu-latest
    permissions:
      # 저장소의 소스를 읽기 위한 권한 설정
      contents: read
      # 패키지를 생성하고 업로드할수 있도록 권한 설정
      packages: write
    
    steps:
    # step에서 사용할 액션을 명시
    # uses : 액션지정
    # run : 명령어 설정
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        # open jdk배포판 이름
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
